server:
  port: 8020
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  threads:
    virtual:
      enabled: true
  thymeleaf:
    cache: false
  h2:
    console:
      path: /h2-console
    datasource:
      url: jdbc:h2:./sb_dev;MODE=MySQL
      driverClassName: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE